### ISSUE TITLE
pc+移动端怎么渲染不同的页面

### ISSUE THREAD

**Issue by WangZhenHao** [ChanWahFung/nuxt-juejin-project#1]
作者做的这个开源项目真的非常好，我只能赞叹啊~~~

我现在有一个问题就是: 项目是 pc+移动端怎么渲染不同的页面呢

比如: http://www.example.com 
如果是pc端，就是渲染pc端的页面
如果是移动端，就会渲染移动端的页面

这个应该怎么做呢？我看到天猫就是这样子的表现，设备不一样，url是不会改变的
但是页面渲染不一样（不是响应式那套东西）

**Comment by BiYuqi** [comment]
@WangZhenHao 你说的问题是nginx做的
