### ISSUE TITLE
大佬 在线等

### ISSUE THREAD

**Issue by Blizzard-liu** [ChanWahFung/nuxt-juejin-project#10]
export default function ({ app: { $axios, $cookies } }) {

app: { $axios, $cookies }  这是什么写法 app:  看不懂   还有后面的$axios, $cookies 从哪来的

**Comment by ChanWahFung** [comment]
一个plugin会接受一个参数context，app是context下的一个属性，{}的写法是es6对象解构，方便直接取这个属性。{ $axios, $cookies }解构也是同理，它们两个是来自第三库的注入，配置在nuxt.config.js的modules中。

context 和 plugin 的描述和用法可以去官方文档查阅，另外我有做了一篇笔记&nbsp;https://juejin.cn/post/6844904160324747278，需要的也可以看下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChanWahFung/nuxt-juejin-project"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午2:37
收件人:&nbsp;"ChanWahFung/nuxt-juejin-project"<nuxt-juejin-project@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ChanWahFung/nuxt-juejin-project] 大佬 在线等 (#10)





 
export default function ({ app: { $axios, $cookies } }) {
 
app: { $axios, $cookies }  这是什么写法 app:  看不懂   还有后面的$axios, $cookies 从哪来的

**Comment by Blizzard-liu** [comment]
666,
