### ISSUE TITLE
大佬求问  动态seo有什么方法可以设置吗？

### ISSUE THREAD

**Issue by jiaqianduan** [ChanWahFung/nuxt-juejin-project#15]
项目要用nuxt根据域名设置meta下的值keywords和description，我自己写了个plugin/global配置title和meta，在本地查看源代码可以看到meta下添加了，部署到线上环境没有作用，大佬等回复！！！

**Comment by zgyandy** [comment]
[head](https://zh.nuxtjs.org/docs/2.x/components-glossary/pages-head)
