### ISSUE TITLE
/components/common/loginModal中的this.ctx是如何挂到全局的

### ISSUE THREAD

**Issue by wanlum** [ChanWahFung/nuxt-juejin-project#16]
<img width="1124" alt="Snipaste_2021-08-02_22-24-56" src="https://user-images.githubusercontent.com/11306760/128102692-3df318fc-c41c-4de0-a982-153c7af8c054.png">

**Comment by ChanWahFung** [comment]
调用登录弹窗时手动传入的，具体可以看同级下index.js的弹窗注册文件
